FROM rayproject/ray:2.50.1-py311-gpu AS build

# installs uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
# This makes sure that logs show up immediately instead of being buffered
ENV PYTHONUNBUFFERED=1

RUN mkdir app
COPY ./tests app/tests
COPY ./uv.lock app/uv.lock
COPY ./pyproject.toml app/pyproject.toml
COPY ./README.md app/README.md

# Extract version and add to a __version__ file which will be read by the service later
RUN echo $(grep -m 1 'version' app/pyproject.toml | sed -E 's/version = "(.*)"/\1/') > /app/__version__

# copying source code
COPY ./src/ app/src/
WORKDIR "/app"

RUN echo "Installing package"
# installs package
RUN uv sync --frozen
ENV PATH="/app/.venv/bin:$PATH"


# Final
FROM build

